Repository selab-hs/glass-bottle, pull requests merged in 2023-06, with the labels that each got.

#39 [ Feature/slack-log] 슬랙 로그 연동 (#18)
  build.gradle
  src/main/java/com/service/core/member/application/MemberService.java
  src/main/java/com/service/core/member/infrastructure/MemberRepository.java
  src/main/java/com/service/core/slack/presentation/SlackSchedulerService.java
  src/main/resources/logback-slack.xml
Labels: develop

#44 [Fix/actuator] Swagger3.0, Spring actuator 호환성 문제 해결
  build.gradle
  src/main/java/com/service/core/config/swagger/SpringfoxHandlerConfig.java
Labels: bug

#54 ♻️[Feature/login] 회원가입 서비스 관리 예외 처리 및 member 생성 방식 수정
  src/main/java/com/service/core/auth/application/AuthUserService.java
  src/main/java/com/service/core/auth/domain/UserDetail.java
  src/main/java/com/service/core/auth/presentation/AuthMemberArgumentResolver.java
  src/main/java/com/service/core/error/dto/ErrorMessage.java
  src/main/java/com/service/core/error/exception/member/DuplicatedMemberException.java
  src/main/java/com/service/core/error/exception/member/EmailFormatMismatchException.java
  src/main/java/com/service/core/error/exception/member/NotAuthorizedException.java
  src/main/java/com/service/core/error/exception/member/NotEqualsMemberInfoException.java
  src/main/java/com/service/core/member/application/MemberService.java
  src/main/java/com/service/core/member/convert/MemberConvert.java
  src/main/java/com/service/core/member/domain/User.java
  src/main/java/com/service/core/member/domain/vo/Email.java
  src/main/java/com/service/core/member/domain/vo/MbtiType.java
  src/main/java/com/service/core/member/dto/request/CreateMemberRequest.java
  src/main/java/com/service/core/member/dto/response/UserInfo.java
  src/main/java/com/service/core/member/infrastructure/MemberRepository.java
Labels: develop

#56 [Move/RestTemplate-2] 중복 로직 rest template 코드 제거
  src/main/java/com/service/core/common/resttemplate/RestTemplateService.java
  src/main/java/com/service/core/error/GlobalExceptionHandler.java
  src/main/java/com/service/core/slack/application/SlackSchedulerService.java
Labels: bug

#47 [Docs/github-action-1] github action yml 기본 폼 생성
  .github/workflows/action.yml
Labels: documentation

#65 [Feature/Letter-Scheduler-1 ] 편지 스케줄링 구현
  src/main/java/com/service/core/common/utis/LocalDateTimeUtil.java
  src/main/java/com/service/core/letter/application/LetterSchedulerService.java
  src/main/java/com/service/core/letter/application/LetterService.java
  src/main/java/com/service/core/letter/convert/LetterConvert.java
  src/main/java/com/service/core/letter/domain/Letter.java
  src/main/java/com/service/core/letter/domain/LetterInvoice.java
  src/main/java/com/service/core/letter/dto/request/WriteLetterRequest.java
  src/main/java/com/service/core/letter/dto/response/WriteLetterResponse.java
  src/main/java/com/service/core/letter/infrastructure/LetterRepository.java
  src/main/java/com/service/core/letter/vo/LetterState.java
  src/main/java/com/service/core/mbti/domain/converter/MbtiResultConverter.java
  src/main/java/com/service/core/member/application/MemberService.java
  src/main/java/com/service/core/slack/application/SlackSchedulerService.java
Labels: develop

#69 * :bug: ec2 의존성 주입 실패로 인한 slf4j 의존성 추가
  build.gradle
Labels: bug

#72 ♻️[Refactor/validate-64] 편지 작성 시 유효성 검사 실행 구현
  build.gradle
  src/main/java/com/service/core/letter/application/LetterService.java
  src/main/java/com/service/core/letter/application/RandomSend.java
  src/main/java/com/service/core/letter/domain/Letter.java
  src/main/java/com/service/core/letter/domain/LetterInvoice.java
  src/main/java/com/service/core/letter/dto/request/ReplyLetterRequest.java
  src/main/java/com/service/core/letter/dto/request/WriteLetterRequest.java
  src/main/java/com/service/core/letter/infrastructure/LetterRepository.java
  src/main/java/com/service/core/letter/presentation/LetterController.java
  src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
Labels: develop

#73 ✨[Feature/delete-59] 편지 삭제 기능 구현
  src/main/java/com/service/core/error/dto/ErrorMessage.java
  src/main/java/com/service/core/error/exception/letter/InvalidDeleteRequestException.java
  src/main/java/com/service/core/letter/application/LetterService.java
  src/main/java/com/service/core/letter/infrastructure/LetterInvoiceRepository.java
  src/main/java/com/service/core/letter/presentation/LetterController.java
Labels: develop

#80 [Feature/Git-Action-2] action.yml 내용 추가
  .github/workflows/actionCD.yml
  .github/workflows/actionCI.yml
  appspec.yml
  src/test/java/com/service/core/GlassBottleServiceApplicationTests.java
  src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
Labels: develop

#81 [Feature/git-action-2] CodeDeploy 실행 코드 추가
  appspec.yml
  scripts/deploy.sh
Labels: develop

#82 [Fix/git-action] codedeploy 배포 config 수정
  .github/workflows/actionCD.yml
Labels: bug

#85 [Fix/Code Deploy] codedeploy 배포 bucket명 변경
  .github/workflows/actionCD.yml
  appspec.yml
Labels: bug

#86 [Fix/Code Deploy] deploy 배포 관리 yml 파일 수정
  .github/workflows/actionCD.yml
  .github/workflows/actionCI.yml
  appspec.yml
Labels: bug

#92 [Fix/Code depoloy] code deploy 실행 파일 명령어 변경
  scripts/deploy.sh
Labels: bug

#88 ✨[Feature/random-78] 전체 랜덤 대상 설정 구현
  build.gradle
  src/main/java/com/service/core/common/domain/BaseEntity.java
  src/main/java/com/service/core/letter/application/LetterService.java
  src/main/java/com/service/core/letter/application/RandomSend.java
  src/main/java/com/service/core/letter/convert/LetterConvert.java
  src/main/java/com/service/core/letter/presentation/LetterController.java
  src/main/java/com/service/core/member/domain/User.java
  src/main/java/com/service/core/member/infrastructure/MemberRepository.java
  src/test/java/com/service/core/letter/application/SendLetterServiceTest.java
Labels: develop

#96 ✨[Feature/redis-95] Redis Cache 기능을 적용한다.
  scripts/deploy.sh
  src/main/java/com/service/core/config/redis/RedisConfig.java
  src/main/java/com/service/core/letter/application/RandomSend.java
  src/main/java/com/service/core/letter/presentation/LetterController.java
  src/main/java/com/service/core/member/infrastructure/MemberRepository.java
Labels: develop

#97 [Fix/cicd] codedeploy 설정 디렉토리 변경
  .github/workflows/actionCICD.yml
  appspec.yml
  scripts/deploy.sh
Labels: bug

#98 [Fix/cicd] deploy 명령어 수정
  scripts/deploy.sh
Labels: bug

#99 [Fix/CI-CD] 배포 파일 실행
  scripts/deploy.sh
Labels: bug

#102 :sparkles: [Feature/mbti quiz] 라운드 카테고리 결과 mbti 별로 퍼센트 결과 출력 기능
  .github/workflows/actionCICD.yml
  src/main/java/com/service/core/common/response/dto/ResponseMessage.java
  src/main/java/com/service/core/letter/domain/Letter.java
  src/main/java/com/service/core/mbti/application/MbtiService.java
  src/main/java/com/service/core/mbti/domain/MbtiQuizHistory.java
  src/main/java/com/service/core/mbti/domain/converter/MbtiResultConverter.java
  src/main/java/com/service/core/mbti/dto/response/ReadMbtiQuizRoundResultResponse.java
  src/main/java/com/service/core/mbti/infrastructure/MbtiQuizHistoryRepository.java
  src/main/java/com/service/core/mbti/presentation/MbtiController.java
Labels: develop

#104 ✨[Feature/jacoco-103] Jacoco 기능 추가
  build.gradle
Labels: develop

#106 ✨[Feature/jacoco-105] Fixture Monkey 기능 추가
  build.gradle
Labels: develop

#110 ♻️ [Feature/mbti quiz] mbti quiz 고도화
  src/main/java/com/service/core/error/dto/ErrorMessage.java
  src/main/java/com/service/core/error/exception/mbti/AmbiguousResultException.java
  src/main/java/com/service/core/mbti/application/MbtiMetadataService.java
  src/main/java/com/service/core/mbti/application/MbtiService.java
  src/main/java/com/service/core/mbti/domain/MbtiQuizHistory.java
  src/main/java/com/service/core/mbti/domain/vo/MbtiTest.java
  src/main/java/com/service/core/mbti/domain/vo/converter/MbtiResultConverter.java
  src/main/java/com/service/core/mbti/dto/request/create/CreateQuizRequest.java
  src/main/java/com/service/core/mbti/infrastructure/MbtiQuizHistoryRepository.java
  src/main/java/com/service/core/mbti/presentation/MbtiController.java
  src/main/java/com/service/core/member/application/MemberService.java
  src/main/java/com/service/core/member/domain/User.java
  src/main/java/com/service/core/member/dto/request/UpdateMemberMbtiRequest.java
  src/main/java/com/service/core/member/infrastructure/MemberRepository.java
Labels: develop

#112 [Fix/letters] Letter Request 값
  .github/workflows/actionCICD.yml
  appspec.yml
  src/main/java/com/service/core/error/dto/ErrorMessage.java
  src/main/java/com/service/core/error/exception/letter/InvalidSharingLetterRequestException.java
  src/main/java/com/service/core/letter/application/LetterService.java
  src/main/java/com/service/core/letter/infrastructure/LetterInvoiceRepository.java
  src/main/java/com/service/core/letter/presentation/LetterController.java
Labels: bug
